In [1]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
X = np.arange(6).reshape(3, 2)
X                                                 


array([[0, 1],
       [2, 3],
       [4, 5]])

The features of X have been transformed from (X_1, X_2) to (1, X_1, X_2, X_1^2, X_1X_2, X_2^2)

class sklearn.preprocessing.PolynomialFeatures(degree=2, interaction_only=False, include_bias=True)

In [3]:
poly = PolynomialFeatures(3)
poly.fit_transform(X)                             


array([[   1.,    0.,    1.,    0.,    0.,    1.,    0.,    0.,    0.,
           1.],
       [   1.,    2.,    3.,    4.,    6.,    9.,    8.,   12.,   18.,
          27.],
       [   1.,    4.,    5.,   16.,   20.,   25.,   64.,   80.,  100.,
         125.]])

In [4]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer
transformer = FunctionTransformer(np.log1p)
X = np.array([[0, 1], [2, 3]])
transformer.transform(X)

array([[ 0.        ,  0.69314718],
       [ 1.09861229,  1.38629436]])

In [11]:
np.log(2)

0.69314718055994529

## Binarization

In [27]:
import sklearn.preprocessing as preprocessing

X = np.asarray([[ 1.,-1.,2.],
      [2.,0.,0.],
      [ 0.,  1., -1.]])
print X

[[ 1. -1.  2.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]]


In [19]:


binarizer = preprocessing.Binarizer().fit(X)  # fit does nothing
binarizer

Binarizer(copy=True, threshold=0.0)

In [20]:
binarizer = preprocessing.Binarizer(threshold=1.1)
binarizer.transform(X)

array([[ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  0.]])

## Encoding categorical features

In [32]:
'''
["uses Firefox", "uses Chrome", "uses Safari", "uses Internet Explorer"]. Such features can be efficiently coded as integers,
for instance ["male", "from US", "uses Internet Explorer"] could be expressed as [0, 1, 3] while 
["female", "from Asia", "uses Chrome"] would be [1, 2, 1]
'''



feature = ["uses Firefox", "uses Chrome", "uses Safari", "uses Internet Explorer"]

import sklearn.preprocessing as preprocessing

enc = preprocessing.OneHotEncoder()
enc.fit([[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]])

OneHotEncoder(categorical_features='all', dtype=<type 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [33]:
enc.transform([[0, 1, 3]]).toarray()

array([[ 1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.]])

In [34]:
X

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [36]:
X_normalized = preprocessing.normalize(X, norm='l2')
X_normalized

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [37]:
from sklearn.pipeline import Pipeline

In [44]:
SLO = {"SLO1" : 1, "SLO2": 2, "SLO3": 3}
VNFC = {"VNFC1":1,"VNFC2":2,"VNFC3":3}

In [54]:
config = (np.asarray([SLO["SLO2"], VNFC["VNFC3"]])).reshape(-1,1)

In [55]:
enc = preprocessing.OneHotEncoder()
enc.fit(config)

OneHotEncoder(categorical_features='all', dtype=<type 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [56]:
enc.transform(config).toarray()

array([[ 1.,  0.],
       [ 0.,  1.]])

In [60]:
import os
print(os.__doc__)

OS routines for NT or Posix depending on what system we're on.

This exports:
  - all functions from posix, nt, os2, or ce, e.g. unlink, stat, etc.
  - os.path is one of the modules posixpath, or ntpath
  - os.name is 'posix', 'nt', 'os2', 'ce' or 'riscos'
  - os.curdir is a string representing the current directory ('.' or ':')
  - os.pardir is a string representing the parent directory ('..' or '::')
  - os.sep is the (or a most common) pathname separator ('/' or ':' or '\\')
  - os.extsep is the extension separator ('.' or '/')
  - os.altsep is the alternate pathname separator (None or '/')
  - os.pathsep is the component separator used in $PATH etc
  - os.linesep is the line separator in text files ('\r' or '\n' or '\r\n')
  - os.defpath is the default search path for executables
  - os.devnull is the file path of the null device ('/dev/null', etc.)

Programs that import and use 'os' stand a better chance of being
portable between different platforms.  Of course, they must then
onl

In [61]:
result = map(lambda x:int(x) ,raw_input().split())
result

1 2 3 4


[1, 2, 3, 4]

In [66]:
def func(x):
    if abs(x)<1000:
        return func(x*x)
    else:
        return x

In [69]:
func(2)

65536

In [82]:
from pprint import pprint 
import config.config as conf

print('The configuration \n')
pprint(conf.settings)

The configuration 

{'SLA': {'desc': 'This is a description*',
         'url': 'https://github.com/heekof/',
         'user': 'donny'},
 'SLO': ['slo1', 'slo2', 'slo3'],
 'config': {'chunksize': 1600,
            'conf_dir': 'config/',
            'conf_file': 'config.py',
            'log_dir': 'log/',
            'log_file': 'main.log',
            'path': '../TNSM/data/Cleaned/'},
 'data': {'path': 'data/'},
 'db': {'host': 'http://mysql.example.com', 'user': 'lebowski'},
 'repo': 'C:\\Users\\CQMQ6347\\CloudStation\\Main\\Work\\'}


In [95]:
def gen(x):
    for i in range(1,x):
        yield i
next(gen(10))

1

In [98]:
it = iter(gen(10))

In [102]:
for i in it:
    print next(it)

5
7
9


In [108]:
17 % 3

2.0

Loading data...
9 train sequences
9 test sequences
Pad sequences (samples x time)
x_train shape: (9L, 80L)
x_test shape: (9L, 80L)
Build model...
Train...
Train on 9 samples, validate on 9 samples
Epoch 1/15


IndexError: index 3951 is out of bounds for size 10
Apply node that caused the error: AdvancedSubtensor1(embedding_2/embeddings, Reshape{1}.0)
Toposort index: 71
Inputs types: [TensorType(float32, matrix), TensorType(int32, vector)]
Inputs shapes: [(10L, 128L), (720L,)]
Inputs strides: [(512L, 4L), (4L,)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Reshape{3}(AdvancedSubtensor1.0, MakeVector{dtype='int64'}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "C:\Users\CQMQ6347\AppData\Local\Continuum\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\CQMQ6347\AppData\Local\Continuum\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\CQMQ6347\AppData\Local\Continuum\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-38-f6e287ceb392>", line 46, in <module>
    model.add(Embedding(max_features, 128))
  File "C:\Users\CQMQ6347\AppData\Local\Continuum\Anaconda2\lib\site-packages\keras\models.py", line 433, in add
    layer(x)
  File "C:\Users\CQMQ6347\AppData\Local\Continuum\Anaconda2\lib\site-packages\keras\engine\topology.py", line 585, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\CQMQ6347\AppData\Local\Continuum\Anaconda2\lib\site-packages\keras\layers\embeddings.py", line 120, in call
    out = K.gather(self.embeddings, inputs)
  File "C:\Users\CQMQ6347\AppData\Local\Continuum\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 417, in gather
    y = reference[indices]

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.